export type QuestionType =
  | 'single'      // 단일 선택
  | 'multi'       // 복수 선택
  | 'multi_max'   // 복수 선택 (최대 n개 제한)
  | 'single_with_other'; // 단일 선택 + 기타 주관식

export interface Question {
  id: string;                    // q1, q2, ...
  dbColumn: string;              // DB 컬럼명 (q1_grade 등)
  otherColumn?: string;          // 기타 주관식 저장 컬럼
  type: QuestionType;
  required: boolean;
  title: string;
  description?: string;
  options: string[];
  maxSelect?: number;            // multi_max용
  condition?: {                  // 조건부 표시용
    dependsOn: string;
    includesAny: string[];
  };
}

export interface Section {
  id: number;
  title: string;
  description?: string;
  questions: Question[];
}

export const BANK_SURVEY_SECTIONS: Section[] = [
  // ===== 섹션 1: 기본 프로필 =====
  {
    id: 1,
    title: '섹션 1. 기본 프로필',
    description: '먼저 간단한 기본 정보를 여쭙겠습니다.',
    questions: [
      {
        id: 'q1',
        dbColumn: 'q1_grade',
        type: 'single',
        required: true,
        title: '현재 등급은 어떻게 되십니까?',
        options: ['특선', '우수', '선발'],
      },
      {
        id: 'q2',
        dbColumn: 'q2_age_group',
        type: 'single',
        required: true,
        title: '연령대는 어떻게 되십니까?',
        options: ['20대 이하', '30-34세', '35-39세', '40-44세', '45-49세', '50세 이상'],
      },
      {
        id: 'q3',
        dbColumn: 'q3_career',
        type: 'single',
        required: true,
        title: '선수 경력은 몇 년 되셨습니까?',
        options: ['3년 이하', '4~7년', '8~12년', '13~20년', '20년 초과'],
      },
      {
        id: 'q4',
        dbColumn: 'q4_region',
        type: 'single',
        required: true,
        title: '훈련지 권역은 어디입니까?',
        options: [
          '수도권 (동서울·김포·청평·서울개인·경기개인·광명)',
          '영남권 (수성·금정·창원A·김해B·부산개인)',
          '중부권 (세종·청주·대전개인·대전도안·충남계룡·충남개인)',
          '호남권 (동광주·광주개인)',
        ],
      },
    ],
  },
  // ===== 섹션 2: 소득 구조 =====
  {
    id: 2,
    title: '섹션 2. 소득 구조',
    description: '소득 관련 질문은 모두 구간(범위)으로만 묻습니다. 정확한 금액은 요구하지 않습니다.',
    questions: [
      {
        id: 'q5',
        dbColumn: 'q5_prize_range',
        type: 'single',
        required: true,
        title: '작년(2025년) 한 해 세전 상금 총액은 대략 얼마였습니까?',
        options: [
          '2,000만원 이하',
          '2,000만원 초과 ~ 4,000만원 이하',
          '4,000만원 초과 ~ 6,000만원 이하',
          '6,000만원 초과 ~ 8,000만원 이하',
          '8,000만원 초과 ~ 1억원 이하',
          '1억원 초과 ~ 1.5억원 이하',
          '1.5억원 초과 ~ 2억원 이하',
          '2억원 초과 ~ 2억 5천만원 이하',
          '2억 5천만원 초과',
        ],
      },
      {
        id: 'q6',
        dbColumn: 'q6_income_trend',
        type: 'single',
        required: true,
        title: '최근 3년간(2023~2025) 본인의 상금 총액은 어떤 추이였습니까?',
        options: [
          '꾸준히 증가 (등급 상승 포함)',
          '큰 변동 없음 (비슷한 수준 유지)',
          '해마다 들쭉날쭉 (변동 큼)',
          '꾸준히 감소',
          '3년 미만 경력이라 해당 없음',
        ],
      },
      {
        id: 'q7',
        dbColumn: 'q7_side_income',
        type: 'multi',
        required: true,
        title: '상금 외에 정기적인 부수입이 있으십니까?',
        description: '해당하는 것을 모두 선택해 주세요.',
        options: [
          '없음 (상금만)',
          '지도/코칭 수입',
          '유튜브·SNS·콘텐츠 수입',
          '광고·협찬 수입',
          '부동산 임대수입',
          '타 사업소득 (자영업 등)',
          '기타',
        ],
      },
      {
        id: 'q8',
        dbColumn: 'q8_income_doc',
        type: 'single',
        required: true,
        title: '국세청 발급 "소득금액증명원" 또는 "종합소득세 신고확인서"를 발급받으신 경험이 있으십니까?',
        options: [
          '매년 발급받아 사용 중 (대출·임대 등 용도)',
          '필요할 때 발급해 본 적 있음',
          '발급해 본 적 없음 (발급 방법 모름)',
          '기타',
        ],
      },
    ],
  },
  // ===== 섹션 3: 상금 계좌 =====
  {
    id: 3,
    title: '섹션 3. 상금 입금 계좌',
    description: '본 설문의 핵심 섹션입니다. 은행 협상 조건을 결정하는 중요한 질문들입니다.',
    questions: [
      {
        id: 'q9',
        dbColumn: 'q9_prize_bank',
        otherColumn: 'q9_prize_bank_other',
        type: 'single_with_other',
        required: true,
        title: '현재 공단에서 지급하는 상금은 어느 은행 계좌로 입금받고 계십니까?',
        options: [
          'KB국민은행', '신한은행', '우리은행', '하나은행', 'NH농협은행',
          'IBK기업은행', 'SC제일은행', '씨티은행', '카카오뱅크', '토스뱅크',
          '케이뱅크', '지방은행 (부산·경남·대구·광주·전북·제주 등)',
          '새마을금고·신협·우체국',
          '기타',
        ],
      },
      {
        id: 'q10',
        dbColumn: 'q10_bank_reason',
        type: 'multi',
        required: true,
        title: '상금 입금 계좌를 현재 은행으로 정한 이유는 무엇입니까?',
        description: '해당하는 것을 모두 선택해 주세요.',
        options: [
          '원래 주거래 은행이라서',
          '공단 지급 시 기본 지정돼서 (당시에 별 생각 없이)',
          '해당 은행 대출을 쓰고 있어서',
          '수수료·접근성이 편해서',
          '가족·지인 권유',
          '특별한 이유 없음',
          '기타',
        ],
      },
      {
        id: 'q11',
        dbColumn: 'q11_transfer_intent',
        type: 'single',
        required: true,
        title: '만약 노조가 A은행과 협약을 맺어서 "상금 계좌를 A은행으로 옮기면 대출금리 0.5~1.0%p 인하" 같은 혜택을 받는다면, 상금 계좌를 옮기실 의향이 있으십니까?',
        options: [
          '혜택 확인 후 바로 옮길 의향 있음',
          '조건(금리 인하 폭)에 따라 검토',
          '웬만하면 현재 은행 유지하고 싶음',
          '절대 옮기고 싶지 않음',
        ],
      },
      {
        id: 'q12',
        dbColumn: 'q12_transfer_conditions',
        type: 'multi_max',
        maxSelect: 3,
        required: true,
        title: '상금 계좌를 옮기기 위해 가장 중요한 조건은 무엇입니까?',
        description: '최대 3개까지 선택해 주세요.',
        options: [
          '대출 금리 인하 (신용대출·마통)',
          '주택담보대출 금리 인하',
          '예금·적금 금리 우대',
          '마이너스통장 한도 상향',
          '카드 연회비 면제·캐시백',
          '수수료 면제 (ATM·이체 등)',
          '노조 조합원 전용 대출상품',
          '보험·연금 상품 할인',
          '기타',
        ],
      },
    ],
  },
  // ===== 섹션 4: 금융상품 보유 =====
  {
    id: 4,
    title: '섹션 4. 현재 금융상품 보유 현황',
    description: '대출 금액·금리 문항은 구간(범위)으로만 묻습니다.',
    questions: [
      {
        id: 'q13',
        dbColumn: 'q13_loans_held',
        type: 'multi',
        required: true,
        title: '현재 본인 명의로 보유 중인 금융상품을 모두 선택해 주세요.',
        options: [
          '마이너스통장 (한도대출)',
          '신용대출 (일반 신용대출·사잇돌·햇살론 등)',
          '주택담보대출 (아파트·빌라·주택 구입용)',
          '전세자금대출',
          '자동차 담보대출 또는 할부금융',
          '카드론 또는 현금서비스',
          '보험계약대출 (약관대출)',
          'P2P·저축은행·대부업체 대출',
          '해당 없음 (대출 보유하지 않음)',
        ],
      },
      {
        id: 'q14',
        dbColumn: 'q14_negative_account_limit',
        type: 'single',
        required: false,
        title: '마이너스통장 한도는 대략 얼마입니까?',
        description: '마이너스통장을 보유하신 경우만 응답해 주세요.',
        condition: {
          dependsOn: 'q13',
          includesAny: ['마이너스통장 (한도대출)'],
        },
        options: [
          '1,000만원 이하',
          '1,000만원 초과 ~ 3,000만원 이하',
          '3,000만원 초과 ~ 5,000만원 이하',
          '5,000만원 초과 ~ 7,000만원 이하',
          '7,000만원 초과 ~ 1억원 이하',
          '1억원 초과',
        ],
      },
      {
        id: 'q15',
        dbColumn: 'q15_credit_loan_balance',
        type: 'single',
        required: false,
        title: '신용대출 잔액(남은 대출금)은 대략 얼마입니까?',
        description: '신용대출을 보유하신 경우만 응답해 주세요.',
        condition: {
          dependsOn: 'q13',
          includesAny: ['신용대출 (일반 신용대출·사잇돌·햇살론 등)'],
        },
        options: [
          '1,000만원 이하',
          '1,000만원 초과 ~ 3,000만원 이하',
          '3,000만원 초과 ~ 5,000만원 이하',
          '5,000만원 초과 ~ 7,000만원 이하',
          '7,000만원 초과 ~ 1억원 이하',
          '1억원 초과',
        ],
      },
      {
        id: 'q16',
        dbColumn: 'q16_mortgage_balance',
        type: 'single',
        required: false,
        title: '주택담보대출 또는 전세자금대출 잔액은 대략 얼마입니까?',
        description: '해당 대출을 보유하신 경우만 응답해 주세요.',
        condition: {
          dependsOn: 'q13',
          includesAny: ['주택담보대출 (아파트·빌라·주택 구입용)', '전세자금대출'],
        },
        options: [
          '5,000만원 이하',
          '5,000만원 초과 ~ 1억원 이하',
          '1억원 초과 ~ 2억원 이하',
          '2억원 초과 ~ 3억원 이하',
          '3억원 초과 ~ 5억원 이하',
          '5억원 초과',
        ],
      },
      {
        id: 'q17',
        dbColumn: 'q17_avg_interest_rate',
        type: 'single',
        required: false,
        title: '현재 보유 중인 대출 상품들의 평균 금리는 대략 어느 수준입니까?',
        description: '대출을 하나라도 보유하신 경우만 응답해 주세요.',
        condition: {
          dependsOn: 'q13',
          includesAny: [
            '마이너스통장 (한도대출)',
            '신용대출 (일반 신용대출·사잇돌·햇살론 등)',
            '주택담보대출 (아파트·빌라·주택 구입용)',
            '전세자금대출',
            '자동차 담보대출 또는 할부금융',
            '카드론 또는 현금서비스',
            '보험계약대출 (약관대출)',
            'P2P·저축은행·대부업체 대출',
          ],
        },
        options: [
          '4% 미만',
          '4% 이상 ~ 5% 미만',
          '5% 이상 ~ 6% 미만',
          '6% 이상 ~ 7% 미만',
          '7% 이상 ~ 9% 미만',
          '9% 이상 ~ 15% 미만 (2금융권 수준)',
          '15% 이상 (카드론·대부업 수준)',
          '잘 모르겠음',
        ],
      },
      {
        id: 'q18',
        dbColumn: 'q18_rejection_history',
        type: 'single',
        required: true,
        title: '최근 3년 이내에 대출 신청 시 심사 거절이나 한도 축소를 경험한 적이 있으십니까?',
        options: [
          '여러 번 있음 (2회 이상)',
          '한 번 있음',
          '없음',
          '대출 신청 자체를 해본 적이 없음',
        ],
      },
    ],
  },
  // ===== 섹션 5: 대환 의향 =====
  {
    id: 5,
    title: '섹션 5. 대환 의향',
    description: '금리 협상 조건을 결정하는 핵심 섹션입니다.',
    questions: [
      {
        id: 'q19',
        dbColumn: 'q19_refinance_intent',
        type: 'single',
        required: true,
        title: '노조가 특정 은행과 협약을 맺어 현재 쓰고 계신 대출의 금리를 인하할 수 있게 된다면, 대환(갈아타기)할 의향이 있으십니까?',
        options: [
          '적극적으로 대환할 의향 있음',
          '조건 보고 긍정적으로 검토',
          '중립 (별 관심 없음)',
          '웬만하면 현재 은행 유지',
          '절대 옮기고 싶지 않음',
          '현재 대출이 없어서 해당 없음',
        ],
      },
      {
        id: 'q20',
        dbColumn: 'q20_rate_threshold',
        type: 'single',
        required: true,
        title: '대환을 결정하기 위해 금리가 얼마나 낮아져야 움직이실 것 같습니까?',
        options: [
          '0.3%p 이상 낮아지면 옮김',
          '0.5%p 이상 낮아지면 옮김',
          '0.7%p 이상 낮아지면 옮김',
          '1.0%p 이상 낮아져야 옮김',
          '1.5%p 이상 낮아져야 옮김',
          '금리와 상관없이 현재 유지',
          '현재 대출이 없어서 해당 없음',
        ],
      },
      {
        id: 'q21',
        dbColumn: 'q21_new_loan_intent',
        type: 'single',
        required: true,
        title: '대환이 아니라 신규로 조합원 전용 대출·마통을 받으실 의향이 있으십니까?',
        options: [
          '적극적으로 신규 발급 의향 있음',
          '조건 보고 긍정적으로 검토',
          '중립',
          '필요 시에만 고려',
          '전혀 관심 없음',
        ],
      },
      {
        id: 'q22',
        dbColumn: 'q22_concerns',
        type: 'multi_max',
        maxSelect: 3,
        required: true,
        title: '대환·신규 발급을 망설이게 만드는 가장 큰 걱정은 무엇입니까?',
        description: '최대 3개까지 선택해 주세요.',
        options: [
          '중도상환수수료 부담',
          '심사·서류 절차가 복잡할 것 같음',
          '신용점수 하락 걱정',
          '기존 은행과의 관계·거래 이력 유지하고 싶음',
          '개인사업자라 심사에서 거절될까 걱정',
          '상금이 변동적이라 대출 자체가 부담',
          '협약 은행 지점이 멀거나 접근성 떨어질 것',
          '특별히 걱정되는 것 없음',
          '기타',
        ],
      },
      {
        id: 'q23',
        dbColumn: 'q23_timing',
        type: 'single',
        required: true,
        title: '대환·신규 발급 시점으로 언제가 가장 적절하다고 생각하십니까?',
        options: [
          '협약 체결 즉시 (1개월 이내)',
          '3개월 이내',
          '6개월 이내',
          '1년 이내',
          '시기에 상관없이 필요할 때',
        ],
      },
    ],
  },
  // ===== 섹션 6: 신규 상품 수요 =====
  {
    id: 6,
    title: '섹션 6. 신규 상품 수요',
    questions: [
      {
        id: 'q24',
        dbColumn: 'q24_new_products',
        type: 'multi',
        required: true,
        title: '협약 은행에서 조합원 우대 조건으로 제공된다면 가입·발급할 의향이 있는 상품을 모두 선택해 주세요.',
        options: [
          '적금 (정기적금·자유적금)',
          '정기예금',
          '주택청약종합저축',
          '체크카드',
          '신용카드',
          'ISA 계좌 (개인종합자산관리계좌)',
          'IRP 또는 연금저축 (퇴직연금·노후 대비)',
          '보험 (실손·종신·저축성 등)',
          '외환·환전 서비스 (해외 전지훈련·해외 여행용)',
          '대여금고',
          '해당 없음 (대출 외에 추가 가입 의향 없음)',
        ],
      },
      {
        id: 'q25',
        dbColumn: 'q25_retirement_prep',
        type: 'multi',
        required: true,
        title: '현재 퇴직 후 노후 대비를 어떻게 하고 계십니까?',
        description: '해당하는 것을 모두 선택해 주세요.',
        options: [
          '국민연금만 납부 중',
          '개인연금저축 가입 중',
          'IRP (개인형 퇴직연금) 가입 중',
          '연금보험 가입 중',
          '부동산 투자',
          '주식·펀드 등 금융투자',
          '사업체 운영·소유',
          '특별히 준비하고 있지 않음',
          '기타',
        ],
      },
      {
        id: 'q26',
        dbColumn: 'q26_union_support',
        otherColumn: 'q26_other',
        type: 'multi_max',
        maxSelect: 3,
        required: true,
        title: '은행 협약과 별개로, 노조가 제공해줬으면 하는 금융 관련 지원이 있다면 무엇입니까?',
        description: '최대 3개까지 선택해 주세요.',
        options: [
          '개인사업자 세무 상담 (종합소득세·부가세 등)',
          '노후 설계 컨설팅',
          '부동산·주택담보대출 전문 상담',
          '투자·재테크 교육',
          '은퇴 후 제2의 직업 설계',
          '가족 대상 금융 상담 (자녀 교육비·보험 등)',
          '대출 거절 사유 분석·대응 지원',
          '부채 구조조정·채무 상담',
          '특별히 원하는 것 없음',
          '기타',
        ],
      },
    ],
  },
  // ===== 섹션 7: 서류 + 노조 역할 =====
  {
    id: 7,
    title: '섹션 7. 서류 준비 및 노조 역할',
    description: '마지막 섹션입니다. 응답해 주셔서 감사합니다.',
    questions: [
      {
        id: 'q27',
        dbColumn: 'q27_documents',
        otherColumn: 'q27_other',
        type: 'multi',
        required: true,
        title: '본인 명의로 다음 서류를 발급받거나 준비할 수 있는 상태인 것을 모두 선택해 주세요.',
        options: [
          '사업자등록증 사본',
          '국세청 발급 부가가치세 과세표준증명원',
          '국세청 발급 종합소득세 신고확인서',
          '공단 발급 "계약 선수 증명서"',
          '노조 발급 조합원 확인서',
          '최근 1~3년 상금 입금 내역 (통장 거래내역)',
          '건강보험 자격득실확인서·납부확인서',
          '모르겠음 (이런 서류가 있는지 처음 알았음)',
          '기타',
        ],
      },
      {
        id: 'q28',
        dbColumn: 'q28_session_attendance',
        type: 'single',
        required: true,
        title: '노조가 은행과 협약을 체결한 후, 조합원 대상 설명회를 연다면 참석하실 의향이 있으십니까?',
        options: [
          '오프라인 설명회 참석 가능 (서울·부산 등 훈련지 근처)',
          '온라인 설명회(줌·유튜브)라면 참석 가능',
          '오프라인·온라인 모두 가능',
          '자료만 서면으로 받아보고 싶음 (설명회 불참)',
          '관심 없음',
        ],
      },
      {
        id: 'q29',
        dbColumn: 'q29_preferred_channel',
        type: 'multi_max',
        maxSelect: 2,
        required: true,
        title: '노조에서 은행 협약 관련 정보를 받을 때 가장 편한 채널은 무엇입니까?',
        description: '최대 2개까지 선택해 주세요.',
        options: [
          '카카오톡 단체방·채널',
          '문자(SMS) 메시지',
          '이메일',
        ],
      },
      {
        id: 'q30',
        dbColumn: 'q30_union_role',
        otherColumn: 'q30_other',
        type: 'multi_max',
        maxSelect: 3,
        required: true,
        title: '은행 협약 과정에서 노조가 가장 집중해서 해줬으면 하는 역할은 무엇입니까?',
        description: '최대 3개까지 선택해 주세요.',
        options: [
          '금리 협상 (최대한 낮은 금리 확보)',
          '심사 간소화·서류 부담 감소',
          '조합원 전용 맞춤 상품 설계',
          '대환 과정 지원 (중도상환수수료 지원 등)',
          '대출 거절 시 노조 차원의 중재·재심사 요청',
          '금융·세무 교육 제공',
          '협약 조건 장기 모니터링 (조건 변경·악화 감시)',
          '은퇴 후 금융 지원까지 연계',
          '기타',
        ],
      },
    ],
  },
];
