-- ============================================================
-- 상금 통계 관련 테이블 및 함수 (2026-01-01)
-- prize_money_standards, prize_allowances, special_rounds,
-- four_day_rounds, fn_prize_stats_full()
-- ============================================================

-- 1. prize_money_standards: 성적상금 기준표 (등급·착순·일차별)
CREATE TABLE IF NOT EXISTS prize_money_standards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year SMALLINT NOT NULL,
  race_type TEXT NOT NULL,        -- '일반','대상GII','왕중왕GI','그랑프리GP'
  day SMALLINT NOT NULL,          -- 일차 (1,2,3)
  grade TEXT NOT NULL,            -- '선발','우수','특선' 등
  rank SMALLINT NOT NULL,         -- 착순
  amount INTEGER NOT NULL         -- 상금액 (천원 단위, ×1000 해서 사용)
);

-- 2. prize_allowances: 출전상금/안전상금/출전준비금 기준표
CREATE TABLE IF NOT EXISTS prize_allowances (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year SMALLINT NOT NULL,
  grade TEXT NOT NULL,
  entry_fee_per_day INTEGER,      -- 출전상금 1일당 (원)
  safety_fee_per_day INTEGER,     -- 안전상금 1일당 (원)
  prep_fee INTEGER,               -- 출전준비금 회차당 (원)
  note TEXT
);
COMMENT ON TABLE prize_allowances IS '연도별 출전상금/안전상금/출전준비금 기준표. 협약서 기반 수동 입력.';
COMMENT ON COLUMN prize_allowances.entry_fee_per_day IS '출전상금 1일당 금액 (원)';
COMMENT ON COLUMN prize_allowances.safety_fee_per_day IS '안전상금 1일당 금액 (원)';
COMMENT ON COLUMN prize_allowances.prep_fee IS '출전 준비금 회차당 금액 (원)';

-- 3. special_rounds: 특별경주 회차 목록
CREATE TABLE IF NOT EXISTS special_rounds (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year SMALLINT NOT NULL,
  round SMALLINT NOT NULL,
  race_type TEXT NOT NULL,        -- '대상GII','왕중왕GI','그랑프리GP'
  source TEXT NOT NULL,           -- 'schedule','auto','manual'
  note TEXT,
  grade_scope TEXT NOT NULL DEFAULT '특선'
    CHECK (grade_scope IN ('전등급', '특선')),
  UNIQUE (year, round)
);
COMMENT ON TABLE special_rounds IS '연도별 특별경주(대상GII/왕중왕GI/그랑프리GP) 회차 목록';
COMMENT ON COLUMN special_rounds.grade_scope IS '전등급: 선발/우수/특선 모두 해당 대회 상금. 특선: 특선만 대회 상금, 우수/선발은 일반경륜 상금';

-- 4. four_day_rounds: 4일 경륜 회차 목록
CREATE TABLE IF NOT EXISTS four_day_rounds (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year SMALLINT NOT NULL,
  round SMALLINT NOT NULL,
  note TEXT
);
COMMENT ON TABLE four_day_rounds IS '4일 경륜 회차 목록. 3일차=2일차 상금, 4일차=3일차 상금 적용';


-- ============================================================
-- 초기 데이터 INSERT
-- ============================================================

-- prize_allowances 데이터 (2015~2025, 등급별 3행씩 = 33행)
INSERT INTO prize_allowances (year, grade, entry_fee_per_day, safety_fee_per_day, prep_fee, note) VALUES
  (2015, '선발', 300000, 60000, 100000, '곽현명 명세서 역산 - 전등급 동일 추정'),
  (2015, '우수', 300000, 60000, 100000, '곽현명 명세서 역산 확인'),
  (2015, '특선', 300000, 60000, 100000, '곽현명 명세서 역산 - 전등급 동일 추정'),
  (2016, '선발', 300000, 60000, 100000, '곽현명 명세서 역산 - 전등급 동일 추정'),
  (2016, '우수', 300000, 60000, 100000, '곽현명 명세서 역산 확인 - 2일 출전'),
  (2016, '특선', 300000, 60000, 100000, '곽현명 명세서 역산 - 전등급 동일 추정'),
  (2017, '선발', 300000, 60000, 100000, '곽현명 명세서 역산 - 전등급 동일 추정'),
  (2017, '우수', 300000, 60000, 100000, '곽현명 명세서 역산 - 전등급 동일 추정'),
  (2017, '특선', 300000, 60000, 100000, '곽현명 명세서 역산 확인'),
  (2018, '선발', 300000, 60000, 100000, '곽현명 명세서 역산 - 전등급 동일 추정'),
  (2018, '우수', 300000, 60000, 100000, '곽현명 명세서 역산 - 전등급 동일 추정'),
  (2018, '특선', 300000, 60000, 100000, '곽현명 명세서 역산 확인 GP'),
  (2019, '선발', 300000, 60000, 100000, '곽현명 명세서 역산 - 전등급 동일 추정'),
  (2019, '우수', 300000, 60000, 100000, '곽현명 명세서 역산 - 전등급 동일 추정'),
  (2019, '특선', 300000, 60000, 100000, '곽현명 명세서 역산 확인 GP 3일'),
  (2020, '선발', 300000, 60000, 100000, '곽현명 명세서 역산 - 전등급 동일 추정'),
  (2020, '우수', 300000, 60000, 100000, '곽현명 명세서 역산 - 전등급 동일 추정'),
  (2020, '특선', 300000, 60000, 100000, '곽현명 명세서 역산 확인 3일'),
  (2021, '선발', 300000, 80000, 100000, '곽현명 명세서 역산 - 전등급 동일 추정'),
  (2021, '우수', 300000, 80000, 100000, '곽현명 명세서 역산 - 전등급 동일 추정'),
  (2021, '특선', 300000, 80000, 100000, '곽현명 명세서 역산 확인 GP 1일'),
  (2022, '선발', 300000, 80000, 100000, '곽현명 명세서 역산 - 전등급 동일 추정'),
  (2022, '우수', 300000, 80000, 100000, '곽현명 명세서 역산 - 전등급 동일 추정'),
  (2022, '특선', 300000, 80000, 100000, '곽현명 명세서 역산 확인 GP 3일'),
  (2023, '선발', 300000, 80000, 100000, '곽현명 명세서 역산 - 전등급 동일 추정'),
  (2023, '우수', 300000, 80000, 100000, '곽현명 명세서 역산 - 전등급 동일 추정'),
  (2023, '특선', 300000, 80000, 100000, '곽현명 명세서 역산 확인 1일'),
  (2024, '선발', 300000, 80000, 100000, '곽현명 명세서 역산 - 전등급 동일 추정'),
  (2024, '우수', 300000, 80000, 100000, '곽현명 명세서 역산 - 전등급 동일 추정'),
  (2024, '특선', 300000, 80000, 100000, '곽현명 명세서 역산 확인 2일'),
  (2025, '선발', 300000, 80000, 100000, '곽현명 명세서 역산 - 전등급 동일 추정'),
  (2025, '우수', 300000, 80000, 100000, '곽현명 명세서 역산 - 전등급 동일 추정'),
  (2025, '특선', 300000, 80000, 100000, '곽현명 명세서 역산 확인 - 2일 출전')
ON CONFLICT DO NOTHING;

-- four_day_rounds 데이터 (18개 회차)
INSERT INTO four_day_rounds (year, round, note) VALUES
  (2016, 33, '광복절 연휴'),
  (2016, 38, '추석 연휴'),
  (2017, 38, '추석 연휴'),
  (2017, 49, '크리스마스 연휴'),
  (2019,  5, '설 연휴'),
  (2019,  7, '연휴'),
  (2021, 40, '추석 연휴'),
  (2021, 41, '한글날 연휴'),
  (2022, 32, '광복절 연휴'),
  (2022, 39, '추석 연휴'),
  (2023, 17, '어린이날 연휴'),
  (2023, 39, '추석 연휴'),
  (2023, 50, '크리스마스 연휴'),
  (2024, 17, '어린이날 연휴'),
  (2024, 39, '추석 연휴'),
  (2024, 50, '크리스마스 연휴'),
  (2025,  9, '삼일절 연휴'),
  (2025, 18, '어린이날 연휴')
ON CONFLICT DO NOTHING;

-- special_rounds grade_scope 업데이트 (전등급 회차)
-- 기본값은 '특선', 아래 회차만 '전등급'으로 변경
-- (special_rounds 데이터 자체는 fetch-special-rounds-from-schedule.ts 스크립트로 생성)
UPDATE special_rounds SET grade_scope = '전등급' WHERE (year, round) IN (
  (2015, 25), (2016, 26), (2017, 24), (2018, 25),  -- 왕중왕GI
  (2019, 26), (2022, 25), (2023, 25), (2024, 25),  -- 왕중왕GI
  (2025, 26),                                        -- 왕중왕GI
  (2022, 48),                                        -- 대상GII 전등급
  (2024, 16), (2024, 40),                            -- 대상GII 전등급
  (2025, 8), (2025, 21), (2025, 39), (2025, 43)     -- 대상GII 전등급
);


-- ============================================================
-- 5. fn_prize_stats_full() 함수
-- ============================================================

CREATE OR REPLACE FUNCTION fn_prize_stats_full()
RETURNS TABLE (
  year SMALLINT,
  performance_prize BIGINT,
  entry_prize BIGINT,
  safety_prize BIGINT,
  prep_prize BIGINT,
  total_prize BIGINT,
  unmatched_count BIGINT,
  has_performance_data BOOLEAN
) LANGUAGE sql STABLE AS $$
WITH 유효일차 AS (
  SELECT rc.id,
    CASE
      WHEN fdr.id IS NOT NULL AND rc.day = 3 THEN 2
      WHEN fdr.id IS NOT NULL AND rc.day = 4 THEN 3
      ELSE rc.day
    END as effective_day
  FROM races rc
  LEFT JOIN four_day_rounds fdr ON fdr.year = rc.year AND fdr.round = rc.round
  WHERE rc.year BETWEEN 2015 AND 2025
),
경주유형 AS (
  -- 경주별로 어떤 prize_money_standards race_type을 써야 하는지 결정
  SELECT
    rc.id as race_id,
    rc.year,
    rc.race_no,
    dcr.id as dcr_id,
    dcr.race_type as grade,
    ed.effective_day,
    CASE
      WHEN sr.id IS NULL THEN '일반'
      WHEN sr.race_type = '그랑프리GP' THEN '그랑프리GP'
      WHEN sr.race_type = '왕중왕GI' THEN '왕중왕GI'
      WHEN sr.race_type = '대상GII'
        AND dcr.race_type IN ('특선','특선준결','특선결승') THEN '대상GII'
      WHEN sr.race_type = '대상GII' AND sr.grade_scope = '전등급'
        AND dcr.race_type IN ('우수','우수준결','우수결승','선발','선발준결','선발결승') THEN '왕중왕GI'
      WHEN sr.race_type = '대상GII' AND sr.grade_scope = '특선'
        AND dcr.race_type IN ('우수','우수준결','우수결승','선발','선발준결','선발결승') THEN '일반'
      ELSE '일반'
    END as pms_race_type
  FROM races rc
  JOIN 유효일차 ed ON ed.id = rc.id
  JOIN decision_card_pages dcp ON dcp.year = rc.year AND dcp.round = rc.round AND dcp.day = rc.day
  JOIN decision_card_races dcr ON dcr.page_id = dcp.id AND dcr.race_no = rc.race_no
  LEFT JOIN special_rounds sr ON sr.year = rc.year AND sr.round = rc.round
  WHERE dcr.race_type IN (
    '선발','선발결승','선발준결','우수','우수결승','우수준결',
    '특선','특선결승','특선준결','그랑프리결승','준결','특우'
  )
),
성적상금 AS (
  SELECT
    rc.year,
    SUM(pms.amount) * 1000 as 성적상금_총액,
    COUNT(CASE WHEN pms.amount IS NULL THEN 1 END) as 미매핑건수
  FROM races rc
  JOIN race_results rr ON rr.race_id = rc.id
  JOIN 경주유형 cu ON cu.race_id = rc.id AND cu.race_no = rc.race_no
  LEFT JOIN prize_money_standards pms ON
    pms.year = rc.year
    AND pms.race_type = cu.pms_race_type
    AND pms.day = cu.effective_day
    AND pms.grade = cu.grade
    AND pms.rank = rr.rank
  WHERE rc.year BETWEEN 2015 AND 2025
    AND rr.rank IS NOT NULL
  GROUP BY rc.year
),
기타상금 AS (
  SELECT
    rc.year,
    COUNT(*) * 300000 as 출전상금_총액,
    COUNT(CASE WHEN rr.withdrawal = '-' THEN 1 END) * pa.safety_fee_per_day as 안전상금_총액,
    COUNT(DISTINCT rr.name || '-' || CAST(rc.round AS TEXT)) * 100000 as 출전준비금_총액
  FROM races rc
  JOIN race_results rr ON rr.race_id = rc.id
  JOIN prize_allowances pa ON pa.year = rc.year AND pa.grade = '특선'
  WHERE rc.year BETWEEN 2015 AND 2025
  GROUP BY rc.year, pa.safety_fee_per_day
)
SELECT
  s.year::SMALLINT,
  COALESCE(s.성적상금_총액, 0)::BIGINT as performance_prize,
  k.출전상금_총액::BIGINT as entry_prize,
  k.안전상금_총액::BIGINT as safety_prize,
  k.출전준비금_총액::BIGINT as prep_prize,
  (COALESCE(s.성적상금_총액, 0) + k.출전상금_총액 + k.안전상금_총액 + k.출전준비금_총액)::BIGINT as total_prize,
  s.미매핑건수::BIGINT as unmatched_count,
  (s.미매핑건수 < 500) as has_performance_data
FROM 성적상금 s
JOIN 기타상금 k ON k.year = s.year
ORDER BY s.year;
$$;
